name = "test-worker"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-02-27"
[build]
command = "npm install pnpm -g && pnpm install && npm run build"
[build.upload]
format = "service-worker"